### ISSUE TITLE
Julia results in benchmark

### ISSUE THREAD

**Issue by KristofferC** [JuliaSparse/MUMPS.jl#5]
Hello,

I was trying some of your benchmarks with my interface to [Pardiso](https://github.com/KristofferC/Pardiso.jl)  and I am getting much better results for backslash in Julia than you are:

| Grid size | Pardiso (sec) | Julia (sec) | Speedup|
| --------- | ------------|-------------|--------|
| 8^3 | 0.00305 | 0.00354 | 1.16009|
| 16^3 | 0.04376 | 0.01373 | 0.31367|
| 24^3 | 0.09810 | 0.06853 | 0.69857|
| 32^3 | 0.25277 | 0.29828 | 1.18005|
| 48^3 | 1.94173 | 2.45429 | 1.26397|
| 64^3 | 9.91453 | 16.01175 | 1.61498|

This was with this file: https://github.com/JuliaSparse/MUMPS.jl/blob/master/tests/benchmarkDivGrad.jl

I tried on both 0.3 and 0.4 with similar results. 

I see that your benchmarks results are quite old, maybe it would be fair to rerun them?

**Comment by lruthotto** [comment]
Thanks Kristoffer, I just updated the results. They are more closely to the ones you have now.

**Comment by KristofferC** [comment]
Thanks. 

Just a thought, it would be cool if there could be some uniformity in the interfaces to all the sparse solvers that you, me and others are making. Then you could make more generic code that works with all types of sparse solvers and users with access to different sparse solvers could still run the same code.

Oh well :)
